/**
 * This file is generated by generate-i18n.mjs
 * Do not edit this file directly
 */
import type enMessage from '../locales/en/messages.json';

export type MessageKey = keyof typeof enMessage;

export type DevLocale = 'en';
